### ISSUE TITLE
Configuration from config file

### ISSUE THREAD

**Issue by EetuK** [EthanSK/restore-terminals-vscode#2]
I propose a new feature where the user could create a configuration file (e.g. `restore-terminals.json`) under the `.vscode` folder and could set the configuration that way. It would be beneficial for users with multiple projects but different terminal setups (and who are not using vscode workspaces).

I have already drafted PR for this feature #3

**Comment by mbruszewski** [comment]
@EthanSK can you please take a look and merge this? Would be great.

**Comment by EthanSK** [comment]
Have done a lot of overhaul, took your changes into account, thanks a lot. The new version is here https://marketplace.visualstudio.com/items?itemName=EthanSK.restore-terminals
