### ISSUE TITLE
Unable to restore a split like attached image.

### ISSUE THREAD

**Issue by BrianGilbert** [EthanSK/restore-terminals-vscode#7]
Can't figure out how to restore the following, anything I try is just opening them as new options in the dropdown list (only one terminal shown at once).

![druxt-breadcrumb js — countycourt-dev 2021-01-25 09-44-55](https://user-images.githubusercontent.com/114017/105646088-fd9d3600-5ef1-11eb-9b4c-507adf10f955.png)

**Comment by EthanSK** [comment]
We have updated it to make it more reliable: https://marketplace.visualstudio.com/items?itemName=EthanSK.restore-terminals

Let me know if this works for you
